export const REQUEST_MESSAGE_MAP = {
  apiUrlErrorText: "接口异常",
  dataErrorText: "数据异常",
  networkErrorText: "网络繁忙",
};

export const WX_APP_INFO = {
  nameTypeInfo: null,
  type: "4",
  typeInfo: null,
  identification: "",
  version: "V1.0",
  appType: "0",
  appTypeInfo: null,
  isFace: "1",
  level: "3",
  jumpPage: "1",
  status: "2",
  statusInfo: null,
  belongType: "1",
  openPc: "1",
  isOauth: "1",
  buriedId: null,
  organType: "1",
  organTypeInfo: null,
  mainIcon:
    "https://api.yunshangnc.com/eeop/image/20230403/28dr0a783mmgezjucpfp.png",
  viceIcon: null,
  agentAddress: null,
  agentAddressIntroduce: null,
  chargePerson: null,
  chargePhone: null,
  contactPerson: null,
  contactPhone: null,
  createdBy: "13",
  createdTime: "2023-04-03 17:41:49",
  updatedBy: "13",
  updatedTime: "2023-04-03 17:47:02",
  clientId: null,
  isEnjoy: null,
  eventType: null,
  isOneWindow: null,
  isLogin: "0",
  address: "",
  addressIntroduce: "",
  introduce: "",
  name: "",
  organ: "",
};
